---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ilyesInzo/configFiles
          #username: if the repo is private we have to ass user/password
          #password:
          search-paths:
            - 'f*' # the folders containing the config files - we use wildcards instead of adding all values
          #repos:
            #perf: #we choose the name we want
              #pattern: # we will give the url pattern that we will use to point that repo
                #- "*/perf"
              #uri: https://github.com/ilyesInzo/secondRepo
              #search-paths:
                #- 'f*'
  security:
    user:
      name: admin
      password: admin
encrypt:
  key: ABCD